### ISSUE TITLE
Step no 9

### ISSUE THREAD

**Issue by kamrulsaad** [mohammadJahid8/robust-express-linting-setup#1]
At your step number 9, I think you mistakenly provided the script to run scripts for eslint check only. I think it should be 
`"prettier:check": "prettier --ignore-path .gitignore --write \"**/*.+(js|ts|json)\"",
    "prettier:fix": "prettier --write .",`

I hope you update it.

Also please make sure to add, `git init` since you need to initialize a git repository to run the husky setup command. 

Other wise everything is perfect. Happy Coding!

**Comment by mohammadJahid8** [comment]
Yes, Thank you so much. Updated!
